### ISSUE TITLE
docker-compose file contains removed 'wait-for' utility

### ISSUE THREAD

**Issue by lhriley** [realies/sqs-insight-docker#1]
Hello,

I was relying on this docker image, and it looks like you decided to remove the `wait-for` utility for some reason which is not obvious. This actually broke our docker-compose as we relied on `wait-for` while [localstack](https://github.com/localstack/localstack) was starting. This is an easy fix on our end, however your own docker-compose file still contains a reference to `wait-for`.

https://github.com/realies/sqs-insight-docker/blob/335a76e18848c0116af933d478f52dc550982b5e/docker-compose.yml#L8

It would be great if you could re-add `wait-for`, but at the very least you should keep your repository consistent for anyone else who might rely on it.

Thanks!

**Comment by realies** [comment]
Thanks for the prompt issue and sorry this broke your instance! Was looking to reduce dependancies as the repository was added to an automatic update cycle based on `sqs-insight` upstream commits, but have indeed overlooked the compose recipe. I think it would be best to mount `wait-for` externally and override the `command` of containers that might need it. Open to suggestions, will update the yml and readme soon.

**Comment by lhriley** [comment]
Thanks for the quick reply. Again, no worries. Not a huge issue.
